/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aerodb;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author jarqu
 */
public class menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());
    int rolID;
    /**
     * Creates new form menu
     */
    public menu(int rolID) {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(580, 400);
        btnAdministrarUsuarios.setVisible(false);
        
        this.rolID = rolID;
        if(rolID == 1){
            btnAdministrarUsuarios.setVisible(true);
        }
        else if(rolID == 2){
            panelEmpleados.setVisible(false);
        }
        else if(rolID == 3){
            panelPasajeros.setVisible(false);
            panelEmpleados.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        btnAdministrarUsuarios = new javax.swing.JLabel();
        panelTablas = new javax.swing.JPanel();
        panelAeropuertos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelPasajeros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelVuelos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        panelTop.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/SkywellAirlines CompassWhite (1).png"))); // NOI18N
        jLabel4.setText("Skywell Airlines");

        lblCerrarSesion.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/ExitWhite.png"))); // NOI18N
        lblCerrarSesion.setText("Cerrar Sesion ");
        lblCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        btnAdministrarUsuarios.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnAdministrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/manage_accounts.png"))); // NOI18N
        btnAdministrarUsuarios.setText("Administrar Usuarios ");
        btnAdministrarUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAdministrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdministrarUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdministrarUsuarios)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdministrarUsuarios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTablas.setBackground(new java.awt.Color(255, 255, 255));

        panelAeropuertos.setBackground(new java.awt.Color(0, 153, 255));
        panelAeropuertos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAeropuertos.setMaximumSize(new java.awt.Dimension(180, 107));
        panelAeropuertos.setMinimumSize(new java.awt.Dimension(180, 107));
        panelAeropuertos.setPreferredSize(new java.awt.Dimension(180, 107));
        panelAeropuertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAeropuertosMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Aeropuertos");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/airlinesWhite.png"))); // NOI18N

        javax.swing.GroupLayout panelAeropuertosLayout = new javax.swing.GroupLayout(panelAeropuertos);
        panelAeropuertos.setLayout(panelAeropuertosLayout);
        panelAeropuertosLayout.setHorizontalGroup(
            panelAeropuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAeropuertosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAeropuertosLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(38, 38, 38))
        );
        panelAeropuertosLayout.setVerticalGroup(
            panelAeropuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAeropuertosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        panelTablas.add(panelAeropuertos);

        panelPasajeros.setBackground(new java.awt.Color(0, 153, 255));
        panelPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPasajeros.setMaximumSize(new java.awt.Dimension(180, 107));
        panelPasajeros.setMinimumSize(new java.awt.Dimension(180, 107));
        panelPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPasajerosMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/GroupWhite.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pasajeros");

        javax.swing.GroupLayout panelPasajerosLayout = new javax.swing.GroupLayout(panelPasajeros);
        panelPasajeros.setLayout(panelPasajerosLayout);
        panelPasajerosLayout.setHorizontalGroup(
            panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasajerosLayout.createSequentialGroup()
                .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPasajerosLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(panelPasajerosLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelPasajerosLayout.setVerticalGroup(
            panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(7, 7, 7))
        );

        panelTablas.add(panelPasajeros);

        panelEmpleados.setBackground(new java.awt.Color(0, 153, 255));
        panelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEmpleados.setMaximumSize(new java.awt.Dimension(180, 107));
        panelEmpleados.setMinimumSize(new java.awt.Dimension(180, 107));
        panelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEmpleadosMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/WorkWhite.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Empleados");

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58))))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        panelTablas.add(panelEmpleados);

        panelVuelos.setBackground(new java.awt.Color(0, 153, 255));
        panelVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVuelos.setMaximumSize(new java.awt.Dimension(180, 107));
        panelVuelos.setMinimumSize(new java.awt.Dimension(180, 107));
        panelVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVuelosMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerodb/flightWhite.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Vuelos");

        javax.swing.GroupLayout panelVuelosLayout = new javax.swing.GroupLayout(panelVuelos);
        panelVuelos.setLayout(panelVuelosLayout);
        panelVuelosLayout.setHorizontalGroup(
            panelVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVuelosLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelVuelosLayout.setVerticalGroup(
            panelVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVuelosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(7, 7, 7))
        );

        panelTablas.add(panelVuelos);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelAeropuertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAeropuertosMouseClicked
        dispose();
        new Aeropuertos(rolID).setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_panelAeropuertosMouseClicked

    private void panelPasajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPasajerosMouseClicked
        dispose();
        new Pasajeros(rolID).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPasajerosMouseClicked

    private void panelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmpleadosMouseClicked
        dispose();
        new Empleados(rolID).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEmpleadosMouseClicked

    private void panelVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVuelosMouseClicked
        dispose();
        new Vuelos(rolID).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVuelosMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        new InicioSesion().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void btnAdministrarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministrarUsuariosMouseClicked
        new Usuarios(rolID).setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnAdministrarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JPanel panelAeropuertos;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelPasajeros;
    private javax.swing.JPanel panelTablas;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelVuelos;
    // End of variables declaration//GEN-END:variables
}
